import type { DocumentSchema } from "@/lib/types/schema"

export const FORM_TEMPLATES: DocumentSchema[] = [
  {
    id: "contact-form",
    type: "form",
    theme: "clean",
    title: "Contact Form",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    components: [
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Full Name",
        placeholder: "John Doe",
        required: true,
      },
      {
        id: crypto.randomUUID(),
        type: "email",
        label: "Email Address",
        placeholder: "john@example.com",
        required: true,
      },
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Subject",
        placeholder: "How can we help?",
        required: true,
      },
      {
        id: crypto.randomUUID(),
        type: "textarea",
        label: "Message",
        placeholder: "Tell us more...",
        required: true,
        rows: 5,
      },
    ],
  },
  {
    id: "feedback-form",
    type: "form",
    theme: "minimal",
    title: "Feedback Form",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    components: [
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Your Name",
        placeholder: "Enter your name",
        required: false,
      },
      {
        id: crypto.randomUUID(),
        type: "email",
        label: "Email (Optional)",
        placeholder: "your@email.com",
        required: false,
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "How would you rate your experience?",
        placeholder: "Select rating",
        required: true,
        options: ["Excellent", "Good", "Average", "Poor", "Very Poor"],
      },
      {
        id: crypto.randomUUID(),
        type: "textarea",
        label: "Additional Comments",
        placeholder: "Share your thoughts...",
        required: false,
        rows: 4,
      },
      {
        id: crypto.randomUUID(),
        type: "checkbox",
        label: "I would recommend this to others",
        defaultValue: false,
      },
    ],
  },
  {
    id: "job-application",
    type: "form",
    theme: "professional",
    title: "Job Application Form",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    components: [
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Full Name",
        placeholder: "First and Last Name",
        required: true,
      },
      {
        id: crypto.randomUUID(),
        type: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        required: true,
      },
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Phone Number",
        placeholder: "+1 (555) 123-4567",
        required: true,
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "Position Applying For",
        placeholder: "Select position",
        required: true,
        options: ["Software Engineer", "Product Manager", "Designer", "Marketing Manager", "Sales Representative"],
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "Years of Experience",
        placeholder: "Select experience level",
        required: true,
        options: ["0-1 years", "1-3 years", "3-5 years", "5-10 years", "10+ years"],
      },
      {
        id: crypto.randomUUID(),
        type: "textarea",
        label: "Why do you want to work here?",
        placeholder: "Tell us about your motivation...",
        required: true,
        rows: 4,
      },
      {
        id: crypto.randomUUID(),
        type: "checkbox",
        label: "I am authorized to work in this country",
        defaultValue: false,
      },
    ],
  },
]
